# TODO: Extra
# [] En algun punto solo como experimento pasa el trafico de la red de Tor
# a tu api y viceversa
#FROM 'nginx:1.23.1-alpine'

# RUN apk --update \ 
# 	--no-cache \ 
# 	add \ 
# 	bash \
# COPY ./network/nginx/default.conf:/etc/nginx/conf.d/default.conf
