# Generated by Django 4.0.6 on 2022-08-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Genero', models.CharField(max_length=50)),
                ('Calification', models.IntegerField()),
                ('URL', models.URLField()),
            ],
        ),
    ]
